# Generated by Django 5.2.5 on 2025-08-21 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestation',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.RemoveField(
            model_name='document',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='lignedocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='lignedocument',
            name='prestation',
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreationDevis', models.DateTimeField(auto_now_add=True)),
                ('statutDevis', models.IntegerField(choices=[(1, 'En Attente'), (2, 'Accepté'), (3, 'Refusé')], default=1)),
                ('numeroDevis', models.CharField(max_length=50, unique=True)),
                ('totalDevis', models.DecimalField(decimal_places=2, max_digits=100)),
                ('lastUpdateDevis', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaireDevis', models.TextField(blank=True, help_text='Entrer un commentaire sur le devis', null=True)),
                ('clientDevis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facture.client')),
                ('devisSaveBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalFacture', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('dateCreationFacture', models.DateTimeField(auto_now_add=True)),
                ('statutFacture', models.IntegerField(choices=[(1, 'Payé'), (2, 'En Attente'), (3, 'Annulée')], default=2)),
                ('numeroFacture', models.CharField(max_length=50, unique=True)),
                ('lastUpdateFacture', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaireFacture', models.TextField(blank=True, help_text='Entrer un commentaire sur la facture', null=True)),
                ('clientFacture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facture.client')),
                ('factureSaveBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(max_length=40)),
                ('descriptionProduit', models.CharField(max_length=400)),
                ('prixUnitaireProduit', models.FloatField(max_length=2)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('devisProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.devis')),
                ('factureProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facturation')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomService', models.CharField(max_length=60)),
                ('descriptionService', models.CharField(max_length=400)),
                ('montantDuService', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePrestationService', models.DateField(auto_now=True, null=True)),
                ('devisService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.devis')),
                ('factureService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facturation')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriePrestation',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='LigneDocument',
        ),
        migrations.DeleteModel(
            name='Prestation',
        ),
    ]
