# Generated by Django 5.2.5 on 2025-09-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_devis_date_transformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturation',
            old_name='dateCreationFacture',
            new_name='dateCreationFacturation',
        ),
    ]
