# Generated by Django 5.2.5 on 2025-08-21 14:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=100)),
                ('emailClient', models.CharField(max_length=150)),
                ('telephoneClient', models.CharField(max_length=50)),
                ('adresseClient', models.CharField(max_length=100)),
                ('sexClient', models.IntegerField(blank=True, choices=[(1, 'Masculin'), (2, 'Féminin')])),
                ('ageClient', models.CharField(max_length=50)),
                ('villeClient', models.CharField(max_length=50)),
                ('dateCreationClient', models.DateTimeField(auto_now_add=True)),
                ('clientSaveBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('typeDocument', models.CharField(choices=[('devis', 'Devis'), ('facture', 'Facture')], max_length=10)),
                ('dateCreationDocument', models.DateField(default=datetime.date.today)),
                ('dateEcheance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('paye', 'Payé'), ('en_attente', 'En attente'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='brouillon', max_length=15)),
                ('sousTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalTva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalTtc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True, default='Paiement à 30 jours')),
                ('dateModification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.client')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateCreationDocument'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paiement', models.DateField(default=datetime.date.today)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile', 'Mobile')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facture.document')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tauxTva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.categorieprestation')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tauxTva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facture.document')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.prestation')),
            ],
        ),
    ]
