# Generated by Django 5.2.6 on 2025-10-29 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitdevis',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
