# Generated by Django 5.2.6 on 2025-10-29 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_produitdevis_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitdevis',
            options={'verbose_name': 'Produit du devis', 'verbose_name_plural': 'Produits du devis'},
        ),
        migrations.AlterField(
            model_name='produitdevis',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
