# Generated by Django 5.2.5 on 2025-08-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_remove_prestation_categorie_remove_document_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sexClient',
            field=models.IntegerField(blank=True, choices=[('Masculin', 'Masculin'), ('Feminin', 'Féminin')]),
        ),
    ]
