# Generated by Django 5.2.6 on 2025-10-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_alter_produitdevis_options_alter_produitdevis_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AlterModelOptions(
            name='facturation',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterField(
            model_name='facturation',
            name='devis_origine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facture_generee', to='facture.devis'),
        ),
    ]
