# Generated by Django 5.2.5 on 2025-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_alter_client_sexclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sexClient',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Feminin', 'Féminin')], max_length=15),
        ),
    ]
