# Generated by Django 5.2.5 on 2025-09-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_alter_client_sexclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='devisProduit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facture.devis'),
        ),
        migrations.AlterField(
            model_name='service',
            name='devisService',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facture.devis'),
        ),
    ]
