# Generated by Django 5.2.6 on 2025-10-30 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_alter_devis_options_alter_facturation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitfacturation',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
