# Generated by Django 5.2.6 on 2025-11-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_produitfacturation_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='mode_reglement',
            field=models.ForeignKey(blank=True, limit_choices_to={'est_actif': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facture.modereglement'),
        ),
    ]
