# Generated by Django 5.2.6 on 2025-11-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_alter_reglement_mode_reglement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturation',
            name='solde_du',
        ),
    ]
